apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://mysql-aws.caxqma0ki34c.us-east-1.rds.amazonaws.com:3306/restaurantdb
  foodcataloguedb_url: jdbc:mysql://mysql-aws.caxqma0ki34c.us-east-1.rds.amazonaws.com:3306/foodcataloguedb
  userdb_url: jdbc:mysql://mysql-aws.caxqma0ki34c.us-east-1.rds.amazonaws.com:3306/userdb

  # Order service d√πng MongoDB Atlas:
  orderdb_url: mongodb+srv://admin:admin@cluster0.w4buqpk.mongodb.net/orderdb?retryWrites=true&w=majority&ssl=true

  # Eureka address
  eureka_service_address: http://eureka-service:8761/eureka/
